# Basic dependabot.yml file with
# minimum configuration for two package managers
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"


  # Enable version updates for python pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"